name: CD

on:
  push:
    branches: [main]

jobs:
  docker-build-and-push:
    name: Docker Build, Test and Push
    uses: ./.github/workflows/docker-build-test.yml
    with:
      push: true
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
